### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by solipsis-project** [solipsis-project/mizu-client#12]
A docker container will be useful for reliable building / deployment and CI.

We should have a CI test that builds Mizu from source using the Dockerfile and creates the environment for further CI tests.

**Comment by webbdays** [comment]
i would like to take this task.

**Comment by solipsis-project** [comment]
It's yours. Thanks for taking an interest.

The project is currently using GitHub Actions for CI, but having a Dockerfile will be a useful way to guarantee that users can build the client locally and play around with it. The Dockerfile should be able to build and install Mizu globally, so that the `mizu` command is in the containers $PATH and can be the container's entrypoint.

Right now the client is a pure Node project, so it should suffice to use the official Node base image (https://hub.docker.com/_/node/), and install the project by running npm.

Since the code is written in typescript, we need to run the tsc compiler before we can do the global install, but after installing the dev dependencies. (Basically, the same set of npm calls as seen in https://github.com/solipsis-project/mizu-client/blob/main/.github/workflows/integration-tests.yaml)
